# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 08:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20160223_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='pub_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 25, 8, 1, 16, 94143), verbose_name='\u53d1\u5e03\u65f6\u95f4'),
        ),
    ]
